import assert from "node:assert/strict";
import { test } from "node:test";
import { parseYarnLockfileGraph } from "../dist/parse-yarn-lockfile.js";

// Captured shape from a real `yarn install --ignore-scripts` run against
// { dependencies: { minimatch: "^3.1.2" } } — trimmed to the fields we parse.
const YARN_LOCK = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


balanced-match@^1.0.0:
  version "1.0.2"
  resolved "https://registry.yarnpkg.com/balanced-match/-/balanced-match-1.0.2.tgz#e83e3a7e3f300b34cb9d87f615fa0cbf357690ee"
  integrity sha512-3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==

brace-expansion@^1.1.7:
  version "1.1.21"
  resolved "https://registry.yarnpkg.com/brace-expansion/-/brace-expansion-1.1.21.tgz#edf4fab5c64d051aea5a8def49aba1c7522279f3"
  integrity sha512-9zeA+KLZNNzglF2TPKRQEDyx6Yby7daAkuy8MiPzpXPsYDWi/DRM8jmwUDxokQjYqBpv5DgPiwD4h4ZZSy1Ujw==
  dependencies:
    balanced-match "^1.0.0"
    concat-map "0.0.1"

concat-map@0.0.1:
  version "0.0.1"
  resolved "https://registry.yarnpkg.com/concat-map/-/concat-map-0.0.1.tgz#d8a96bd77fd68df7793a73036a3ba0d5405d477b"
  integrity sha512-/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==
`;

const PACKAGE_JSON = JSON.stringify({
  name: "yarn-fixture",
  dependencies: { "brace-expansion": "^1.1.7" },
  // Also required transitively by brace-expansion@1.1.21 (via concat-map "0.0.1") — declaring it
  // directly here too should still win as "direct", not get demoted to transitive.
  devDependencies: { "concat-map": "0.0.1" },
});

const PROJECTS = [{ path: ".", packageJsonContent: PACKAGE_JSON }];

test("direct dependency resolved from package.json, not just the lockfile", () => {
  const graph = parseYarnLockfileGraph(YARN_LOCK, PROJECTS).get(".");
  assert.deepEqual(graph.get("brace-expansion@1.1.21"), {
    dependencyType: "direct",
    depth: undefined,
    path: ["brace-expansion"],
    license: undefined,
  });
});

test("package required both directly and transitively reports as direct", () => {
  const graph = parseYarnLockfileGraph(YARN_LOCK, PROJECTS).get(".");
  assert.equal(graph.get("concat-map@0.0.1").dependencyType, "direct");
});

test("transitive-only dependency reports depth 2 with full path", () => {
  const graph = parseYarnLockfileGraph(YARN_LOCK, PROJECTS).get(".");
  assert.deepEqual(graph.get("balanced-match@1.0.2"), {
    dependencyType: "transitive",
    depth: 2,
    path: ["brace-expansion", "balanced-match"],
    license: undefined,
  });
});

// Captured shape from a real `yarn install --ignore-scripts` run against
// { dependencies: { "@babel/core": "^7.24.0" } } — confirms scoped names (quoted, containing
// their own "@") are split correctly in both header and nested dependency lines.
const SCOPED_YARN_LOCK = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.29.7":
  version "7.29.7"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.29.7.tgz#deadbeef"
  integrity sha512-deadbeef==

"@babel/core@^7.24.0":
  version "7.29.7"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.29.7.tgz#deadbeef"
  integrity sha512-deadbeef==
  dependencies:
    "@babel/code-frame" "^7.29.7"
    semver "^6.3.1"

semver@^6.3.1:
  version "6.3.1"
  resolved "https://registry.yarnpkg.com/semver/-/semver-6.3.1.tgz#deadbeef"
  integrity sha512-deadbeef==
`;

const SCOPED_PACKAGE_JSON = JSON.stringify({
  dependencies: { "@babel/core": "^7.24.0" },
});
const SCOPED_PROJECTS = [
  { path: ".", packageJsonContent: SCOPED_PACKAGE_JSON },
];

test("scoped package names parsed correctly in header and dependency lines", () => {
  const graph = parseYarnLockfileGraph(SCOPED_YARN_LOCK, SCOPED_PROJECTS).get(
    ".",
  );
  assert.equal(graph.get("@babel/core@7.29.7").dependencyType, "direct");
  assert.deepEqual(graph.get("@babel/code-frame@7.29.7").path, [
    "@babel/core",
    "@babel/code-frame",
  ]);
  assert.equal(graph.get("semver@6.3.1").depth, 2);
});
